2024-06-08_16-38-34 - INFO in log.py function log_write : test

2024-06-08_16-38-34 - ERROR in log.py function log_write : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 129, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-21-58 - INFO in None function None : test

2024-06-09_21-21-58 - ERROR in None function None : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-22-50 - INFO in None function None : test

2024-06-09_21-22-50 - ERROR in None function None : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 150, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-30-57 - INFO in None function None : test

2024-06-09_21-30-57 - ERROR in None function None : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 156, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-31-38 - INFO in None function None : test

2024-06-09_21-31-38 - ERROR in None function None : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 154, in test
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-33-32 - INFO in H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py function <module> : test

2024-06-09_21-33-32 - ERROR in H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 147, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-09_21-35-09 - INFO in log.py function <module> : test

2024-06-09_21-35-09 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 147, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_00-10-26 - INFO in log.py function <module> : test

2024-06-12_00-10-26 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 145, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_00-15-00 - INFO in log.py function <module> : test

2024-06-12_00-15-00 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 144, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-40-42 - INFO in log.py function <module> : test

2024-06-12_20-40-42 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 150, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-53-34 - INFO in log.py function <module> : test

2024-06-12_20-53-34 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-54-40 - INFO in log.py function <module> : test

2024-06-12_20-54-40 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-54-40 - ERROR in log.py function <module> : 111
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-55-03 - INFO in log.py function <module> : test

2024-06-12_20-55-03 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
2024-06-12_20-55-03 - ERROR in log.py function <module> : test logging
Traceback (most recent call last):
  File "H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\home_security_surveillance\file_process\log.py", line 152, in <module>
    raise ValueError("test logging")
ValueError: test logging
